# Generated by Django 3.1.7 on 2021-03-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20210309_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('uemail', models.CharField(max_length=50)),
                ('uphone', models.IntegerField(max_length=10)),
                ('umsg', models.CharField(max_length=250)),
            ],
        ),
    ]
