# Generated by Django 3.1.7 on 2021-03-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_contact_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='uphone',
            field=models.CharField(max_length=10),
        ),
    ]
