# Generated by Django 3.1.7 on 2021-03-26 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20210312_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sd_name', models.CharField(max_length=50)),
                ('sd_admno', models.CharField(max_length=10)),
                ('sd_course', models.CharField(max_length=50)),
                ('sd_dob', models.CharField(max_length=30)),
                ('sd_guardian', models.CharField(max_length=30)),
                ('sd_address', models.CharField(max_length=100)),
                ('sd_phone', models.CharField(max_length=20)),
                ('sd_guardian_phone', models.CharField(max_length=20)),
                ('sd_room_no', models.CharField(max_length=999)),
                ('sd_feedback', models.CharField(max_length=150)),
                ('sd_remark', models.CharField(max_length=150)),
                ('sd_fees', models.CharField(max_length=50000)),
                ('sd_university_register', models.CharField(max_length=50)),
                ('sd_parent', models.CharField(max_length=150)),
                ('sd_parent_phone', models.CharField(max_length=20)),
            ],
        ),
    ]
