# Generated by Django 3.1.7 on 2021-03-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_auto_20210326_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sd_year',
            field=models.CharField(default=2000, max_length=4),
            preserve_default=False,
        ),
    ]
