# Generated by Django 3.1.7 on 2021-03-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_student_sd_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sd_password',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
