# Generated by Django 3.1.7 on 2021-03-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_student_sd_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=100)),
                ('visitor_contact', models.CharField(max_length=100)),
                ('visitor_student_id', models.CharField(max_length=1000)),
            ],
        ),
    ]
