# Generated by Django 3.1.7 on 2021-03-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='visitor_student_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
