# Generated by Django 3.1.7 on 2021-03-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_visitor_visitor_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='visitor_date',
            field=models.DateField(null=True),
        ),
    ]
