# Generated by Django 3.1.7 on 2021-04-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_visitor_visitor_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auther', models.CharField(max_length=50)),
                ('auther_phone', models.CharField(max_length=20)),
                ('auther_ID', models.CharField(max_length=1000)),
                ('subject', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('body', models.CharField(max_length=500)),
            ],
        ),
    ]
