# Generated by Django 3.1.7 on 2021-04-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0016_auto_20210421_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendace',
            name='id',
        ),
        migrations.AlterField(
            model_name='attendace',
            name='attendace_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
