# Generated by Django 3.1.7 on 2021-04-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0019_auto_20210421_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendace',
            name='sd_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
