# Generated by Django 3.1.7 on 2021-04-25 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0021_auto_20210421_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='fees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sd_id', models.IntegerField()),
                ('date', models.DateField()),
                ('status', models.BooleanField(default=False)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('paid_by', models.CharField(max_length=50)),
                ('transaction', models.CharField(max_length=100)),
                ('mess_fee', models.IntegerField(null=True)),
                ('fine', models.IntegerField(null=True)),
                ('accommodation', models.IntegerField(null=True)),
                ('common', models.IntegerField(null=True)),
                ('total', models.IntegerField()),
                ('student_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.student')),
            ],
        ),
    ]
