# Generated by Django 3.1.7 on 2021-04-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0022_fees'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fees',
            old_name='date',
            new_name='created_date',
        ),
        migrations.AlterField(
            model_name='fees',
            name='paid_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fees',
            name='transaction',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
