# Generated by Django 3.1.7 on 2021-04-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0023_auto_20210425_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
