# Generated by Django 3.1.7 on 2021-04-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0025_auto_20210425_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='month',
            field=models.CharField(max_length=31),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='year',
            field=models.CharField(max_length=5000),
        ),
    ]
