# Generated by Django 3.2 on 2021-04-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0026_auto_20210425_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='warden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_main', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('status', models.BooleanField(default=True)),
                ('is_normal', models.BooleanField(default=True)),
                ('incharge', models.CharField(max_length=50)),
            ],
        ),
    ]
