# Generated by Django 3.2 on 2021-05-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0028_auto_20210430_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='warden',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warden',
            name='password',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
