# Generated by Django 3.2 on 2021-05-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0029_auto_20210502_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='warden',
            name='pic',
            field=models.ImageField(default='default.jpg', upload_to='admin_profile_pic'),
        ),
    ]
