# Generated by Django 3.2 on 2021-05-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0032_auto_20210507_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='fees',
            name='amount_paise',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='fees',
            name='orderid',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
