# Generated by Django 3.2 on 2021-05-10 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0033_auto_20210511_0120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Razorpay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_payment_id', models.CharField(max_length=250)),
                ('razorpay_signature', models.CharField(max_length=250)),
                ('fee_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.fees')),
            ],
        ),
    ]
