# Generated by Django 3.2 on 2021-05-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0034_razorpay'),
    ]

    operations = [
        migrations.AddField(
            model_name='razorpay',
            name='razorpay_order_id',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
