# Generated by Django 3.2 on 2021-05-12 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0036_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='student_info',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='User.student'),
            preserve_default=False,
        ),
    ]
