# Generated by Django 3.2 on 2021-05-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0037_leave_student_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='no_of_day',
            field=models.IntegerField(default=1),
        ),
    ]
