# Generated by Django 3.2 on 2021-05-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0038_leave_no_of_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='reg_day',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='visitor_count',
            field=models.IntegerField(default=1),
        ),
    ]
