# Generated by Django 3.1.4 on 2021-05-25 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0039_auto_20210516_1800'),
        ('User', '0033_auto_20210507_1656'),
    ]

    operations = [
    ]
