# Generated by Django 3.2 on 2021-05-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0041_auto_20210525_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auther', models.CharField(max_length=50)),
                ('auther_phone', models.CharField(max_length=20)),
                ('auther_ID', models.CharField(max_length=1000)),
                ('subject', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('body', models.CharField(max_length=500)),
            ],
        ),
    ]
