# Generated by Django 3.2 on 2021-05-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0042_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='important',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='body',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
