# Generated by Django 3.2 on 2021-06-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0044_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='time',
            field=models.CharField(max_length=10),
        ),
    ]
