# Generated by Django 3.2 on 2021-07-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0047_service_closed'),
    ]

    operations = [
        migrations.CreateModel(
            name='mess_menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('mng', models.CharField(max_length=30)),
                ('noon', models.CharField(max_length=30)),
                ('night', models.CharField(max_length=30)),
            ],
        ),
    ]
