# Generated by Django 3.2 on 2021-07-19 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0048_mess_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodWaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('Bake', models.CharField(max_length=10)),
                ('Consumed', models.CharField(max_length=10)),
            ],
        ),
    ]
