# Generated by Django 3.2 on 2021-07-19 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0049_foodwaste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodwaste',
            name='day',
            field=models.CharField(max_length=15),
        ),
    ]
