# Generated by Django 3.1.4 on 2021-05-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_guest',
            name='room',
            field=models.IntegerField(default=0),
        ),
    ]
