# Generated by Django 3.1.4 on 2021-05-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0002_register_guest_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_guest',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
