# Generated by Django 3.1.4 on 2021-05-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0003_register_guest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_guest',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
