# Generated by Django 3.2 on 2021-05-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0004_auto_20210511_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_guest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
